server:
  port: 9000


spring:
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/db;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /console


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.treevalue.h2.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", "UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


logging:
  level:
    org.springframework.boot: error
